### ISSUE TITLE
Consider moving from SimpleIRC to another IRC library

### ISSUE THREAD

**Issue by JanGe** [JanGe/xdcc#4]
As [SimpleIRC](https://hackage.haskell.org/package/simpleirc) is ~~not in Stackage and~~ [more or less unmaintained](https://github.com/dom96/SimpleIRC/issues/24#issuecomment-198085225), consider moving to another library.

**Comment by cbm80** [comment]
Regarding your latest commit [4ca7cb6](https://github.com/JanGe/xdcc/commit/4ca7cb63fdc94614f2ba5131887ec27f6ca81936) it turns out that exception handling is still somewhat broken. 

This is because simpleIRC forks a thread for handling events which is not properly shut down on disconnecting. This thread will at some point raise an exception on its own. So even your latest commit (or my previous attempt at fixing this), doesn't quite work.

IMO there are three ways of fixing this:
1. fork simpleIRC and add proper code to do what's needed
2. be brutal and never invoke 'disconnect' when using znc
3. use a different library for IRC

**Comment by JanGe** [comment]
SimpleIRC's `connect` function takes a boolean argument which specifies if it should run in a new thread.
It could be worth a shot to tell SimpleIRC to not fork its own thread and instead wrap that call in a `forkIO` and try to catch exceptions.

**Comment by cbm80** [comment]
On Tue, 19 Apr 2016 12:09:05 -0700
Jan Gerlinger notifications@github.com wrote:

> SimpleIRC's `connect` function takes a boolean argument which specifies if it should run in a new thread.
> It could be worth a shot to tell SimpleIRC to not fork its own thread and instead wrap that call in a `forkIO` and try to catch exceptions.

simpleIRC does not export its IrcServer Type, so that's a problem when you're trying to write your own dispatch-loop.

**Comment by JanGe** [comment]
Ok, then I'll have to try to reproduce it.

When exactly does it happen?
- Connected to an IRC network through ZNC
-  `--znc-auto-connect` enabled
- Download is already finished
- MPrivmsg "*status" "disconnect" was sent
- ZNC closes connection
- Calling SimpleIRC's `disconnect` function triggers an exception that is catched

And after that SimpleIRC's `listenLoop` throws an exception? Is it like that?

**Comment by cbm80** [comment]
On Wed, 20 Apr 2016 07:18:40 -0700
Jan Gerlinger notifications@github.com wrote:

> When exactly does it happen?
> - Connected to an IRC network through ZNC
> -  `--znc-auto-connect` enabled
> - Download is already finished
> - MPrivmsg "*status" "disconnect" was sent
> - ZNC closes connection
> - Calling SimpleIRC's `disconnect` function triggers an exception that is catched
> 
> And after that SimpleIRC's `listenLoop` throws an exception? Is it like that?

What happens is:
- MPrivmsg "*status" "disconnect" is send
- ZNC only disconnects from the IRC-server, not from the client (ie. xdcc)
- calling SimpleIRC's `disconnect` function closes the connection
- a few milliseconds pass
- `listenLoop` catches an exception, prints an error message and calls `cleanup`

So the exception is caught, but it looks like an error. What really should happen is that
`disconnect` first terminates `listenLoop` properly and then closes the connection.

**Comment by JanGe** [comment]
Finally had the time to complete the switch. `xdcc-1.1.1` is now using `irc-client`.

@cbm80 Can you check if `xdcc` now behaves better in your case and if not file a new bug?

**Comment by cbm80** [comment]
I had alot of trouble getting the new version to work, mostly because `irc-conduit` (which `irc-client` relies on) silently fails when presented with a self-signed TLS certificate. There's no indication how, where and why it fails and it took me quite a while to figure this out.

The simplest fix turned out to be using a signed cert.

The problem that `xdcc` doesn't send proper `xdcc cancel` messages seems to persist, as does the handling of `ctrl-c` in combination with ZNC.
