### ISSUE TITLE
Allow self-signed certificates when connecting to network

### ISSUE THREAD

**Issue by JanGe** [JanGe/xdcc#8]
@cbm80 writes in #4:

> I had alot of trouble getting the new version to work, mostly because irc-conduit (which irc-client relies on) silently fails when presented with a self-signed TLS certificate. There's no indication how, where and why it fails and it took me quite a while to figure this out.
> 
> The simplest fix turned out to be using a signed cert.

From looking at the code of `irc-conduit`, it actually tries to [do the right thing](https://github.com/barrucadu/irc-conduit/blob/a60a38ea1e9803205de7b43bc3386f92f8390e49/Network/IRC/Conduit.hs#L159):

``` haskell
-- Make the TLS certificate validation a bit more generous. In
-- particular, allow self-signed certificates.
validate cs vc sid cc = do
  -- First validate with the standard function
  res <- (onServerCertificate $ clientHooks cpara) cs vc sid cc
  -- Then strip out non-issues
  return $ filter (`notElem` [UnknownCA, SelfSigned]) res
```

I'll have to debug why that doesn't work as expected.

**Comment by cbm80** [comment]
It does the right thing.

Using a self-signed cert failed with `NoCommonName` or `InvalidName` because I had erroneously entered bogus-data instead of the domain name when I created it. So there's nothing to debug here.

 The only things that do not appear to have changed from the old version are the handling of `ctrl-c` and sending `disconnect` to ZNC prior to closing the connection.

**Comment by JanGe** [comment]
Alright, then I can close this issue again. ;)
Thanks for the quick response!
